<a href="https://colab.research.google.com/github/muralikrishnan2022/Company_Predicted_Performance/blob/main/Company_Predicted_Performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.11.4)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [ ]:
# Load your datasets
train_data = pd.read_csv('/content/drive/MyDrive/train_s.csv')
test_data = pd.read_csv('/content/drive/MyDrive/test_s.csv')

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135000 entries, 0 to 134999
Data columns (total 98 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           135000 non-null  int64
 1   username     134541 non-null  object
 2   name         135000 non-null  object
 3   sex          135000 non-null  object
 4   address      134437 non-null  object
 5   mail         135000 non-null  object
 6   birthdate    134201 non-null  object
 7   Feature_0    135000 non-null  object
 8   Feature_1    134674 non-null  float64
 9   Feature_2    134650 non-null  float64
 10  Feature_3    134674 non-null  float64
 11  Feature_4    134715 non-null  float64
 12  Feature_5    134646 non-null  float64
 13  Feature_6    135000 non-null  object
 14  Feature_7    134724 non-null  float64
 15  Feature_8    134638 non-null  float64
 16  Feature_9    135000 non-null  object
 17  Feature_10   134624 non-null  float64
 18  Feature_11   134686 non-null  float64
 19  Feature_12   134657 non-null  float64
 20  Feature_13   134636 non-null  float64
 21  Feature_14   135000 non-null  object
 22  Feature_15   134703 non-null  float64
 23  Feature_16   134642 non-null  float64
 24  Feature_17   135000 non-null  object
 25  Feature_18   135000 non-null  object
 26  Feature_19   135000 non-null  object
 27  Feature_20   134692 non-null  float64
 28  Feature_21   135000 non-null  object
 29  Feature_22   135000 non-null  object
 30  Feature_23   135000 non-null  object
 31  Feature_24   134643 non-null  float64
 32  Feature_25   134695 non-null  float64
 33  Feature_26   134646 non-null  float64
 34  Feature_27   135000 non-null  object
 35  Feature_28   135000 non-null  object
 36  Feature_29   135000 non-null  object
 37  Feature_30   134689 non-null  float64
 38  Feature_31   134674 non-null  float64
 39  Feature_32   134695 non-null  float64
 40  Feature_33   135000 non-null  object
 41  Feature_34   135000 non-null  object
 42  Feature_35   134724 non-null  float64
 43  Feature_36   134640 non-null  float64
 44  Feature_37   135000 non-null  object
 45  Feature_38   134726 non-null  float64
 46  Feature_39   134692 non-null  float64
 47  Feature_40   135000 non-null  object
 48  Feature_41   134631 non-null  float64
 49  Feature_42   134635 non-null  float64
 50  Feature_43   135000 non-null  object
 51  Feature_44   135000 non-null  object
 52  Feature_45   134659 non-null  float64
 53  Feature_46   134643 non-null  float64
 54  Feature_47   135000 non-null  object
 55  Feature_48   135000 non-null  object
 56  Feature_49   135000 non-null  object
 57  Feature_50   134630 non-null  float64
 58  Feature_51   135000 non-null  object
 59  Feature_52   134612 non-null  float64
 60  Feature_53   135000 non-null  object
 61  Feature_54   134685 non-null  float64
 62  Feature_55   135000 non-null  object
 63  Feature_56   135000 non-null  object
 64  Feature_57   135000 non-null  object
 65  Feature_58   134647 non-null  float64
 66  Feature_59   134677 non-null  float64
 67  Feature_60   134629 non-null  float64
 68  Feature_61   135000 non-null  object
 69  Feature_62   134684 non-null  float64
 70  Feature_63   134685 non-null  float64
 71  Feature_64   134628 non-null  float64
 72  Feature_65   135000 non-null  object
 73  Feature_66   135000 non-null  object
 74  Feature_67   134664 non-null  float64
 75  Feature_68   135000 non-null  object
 76  Feature_69   135000 non-null  object
 77  Feature_70   135000 non-null  object
 78  Feature_71   135000 non-null  object
 79  Feature_72   135000 non-null  object
 80  Feature_73   135000 non-null  object
 81  Feature_74   134722 non-null  float64
 82  Feature_75   135000 non-null  object
 83  Feature_76   134615 non-null  float64
 84  Feature_77   134655 non-null  float64
 85  Feature_78   135000 non-null  object
 86  Feature_79   135000 non-null  object
 87  Feature_80   134711 non-null  float64
 88  Feature_81   134712 non-null  float64
 89  Feature_82   134690 non-null  float64
 90  Feature_83   134704 non-null  float64
 91  Feature_84   134699 non-null  float64
 92  Feature_85   134710 non-null  float64
 93  Feature_86   134700 non-null  float64
 94  Feature_87   134719 non-null  float64
 95  Feature_88   134640 non-null  float64
 96  Feature_89   135000 non-null  object
 97  PERFORMANCE  135000 non-null  object
dtypes: float64(50), int64(1), object(47)
memory usage: 100.9+ MB

In [ ]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 97 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          15000 non-null  int64
 1   username    14939 non-null  object
 2   name        15000 non-null  object
 3   sex         15000 non-null  object
 4   address     14942 non-null  object
 5   mail        15000 non-null  object
 6   birthdate   14918 non-null  object
 7   Feature_0   15000 non-null  object
 8   Feature_1   14959 non-null  float64
 9   Feature_2   14947 non-null  float64
 10  Feature_3   14955 non-null  float64
 11  Feature_4   14973 non-null  float64
 12  Feature_5   14953 non-null  float64
 13  Feature_6   15000 non-null  object
 14  Feature_7   14968 non-null  float64
 15  Feature_8   14953 non-null  float64
 16  Feature_9   15000 non-null  object
 17  Feature_10  14962 non-null  float64
 18  Feature_11  14967 non-null  float64
 19  Feature_12  14963 non-null  float64
 20  Feature_13  14969 non-null  float64
 21  Feature_14  15000 non-null  object
 22  Feature_15  14968 non-null  float64
 23  Feature_16  14945 non-null  float64
 24  Feature_17  15000 non-null  object
 25  Feature_18  15000 non-null  object
 26  Feature_19  15000 non-null  object
 27  Feature_20  14952 non-null  float64
 28  Feature_21  15000 non-null  object
 29  Feature_22  15000 non-null  object
 30  Feature_23  15000 non-null  object
 31  Feature_24  14953 non-null  float64
 32  Feature_25  14970 non-null  float64
 33  Feature_26  14970 non-null  float64
 34  Feature_27  15000 non-null  object
 35  Feature_28  15000 non-null  object
 36  Feature_29  15000 non-null  object
 37  Feature_30  14963 non-null  float64
 38  Feature_31  14963 non-null  float64
 39  Feature_32  14969 non-null  float64
 40  Feature_33  15000 non-null  object
 41  Feature_34  15000 non-null  object
 42  Feature_35  14970 non-null  float64
 43  Feature_36  14957 non-null  float64
 44  Feature_37  15000 non-null  object
 45  Feature_38  14967 non-null  float64
 46  Feature_39  14969 non-null  float64
 47  Feature_40  15000 non-null  object
 48  Feature_41  14954 non-null  float64
 49  Feature_42  14966 non-null  float64
 50  Feature_43  15000 non-null  object
 51  Feature_44  15000 non-null  object
 52  Feature_45  14964 non-null  float64
 53  Feature_46  14956 non-null  float64
 54  Feature_47  15000 non-null  object
 55  Feature_48  15000 non-null  object
 56  Feature_49  15000 non-null  object
 57  Feature_50  14955 non-null  float64
 58  Feature_51  15000 non-null  object
 59  Feature_52  14971 non-null  float64
 60  Feature_53  15000 non-null  object
 61  Feature_54  14964 non-null  float64
 62  Feature_55  15000 non-null  object
 63  Feature_56  15000 non-null  object
 64  Feature_57  15000 non-null  object
 65  Feature_58  14954 non-null  float64
 66  Feature_59  14965 non-null  float64
 67  Feature_60  14956 non-null  float64
 68  Feature_61  15000 non-null  object
 69  Feature_62  14976 non-null  float64
 70  Feature_63  14959 non-null  float64
 71  Feature_64  14968 non-null  float64
 72  Feature_65  15000 non-null  object
 73  Feature_66  15000 non-null  object
 74  Feature_67  14962 non-null  float64
 75  Feature_68  15000 non-null  object
 76  Feature_69  15000 non-null  object
 77  Feature_70  15000 non-null  object
 78  Feature_71  15000 non-null  object
 79  Feature_72  15000 non-null  object
 80  Feature_73  15000 non-null  object
 81  Feature_74  14972 non-null  float64
 82  Feature_75  15000 non-null  object
 83  Feature_76  14966 non-null  float64
 84  Feature_77  14960 non-null  float64
 85  Feature_78  15000 non-null  object
 86  Feature_79  15000 non-null  object
 87  Feature_80  14968 non-null  float64
 88  Feature_81  14965 non-null  float64
 89  Feature_82  14964 non-null  float64
 90  Feature_83  14963 non-null  float64
 91  Feature_84  14972 non-null  float64
 92  Feature_85  14969 non-null  float64
 93  Feature_86  14966 non-null  float64
 94  Feature_87  14968 non-null  float64
 95  Feature_88  14957 non-null  float64
 96  Feature_89  15000 non-null  object
dtypes: float64(50), int64(1), object(46)
memory usage: 11.1+ MB

In [ ]:
train_data.isnull().sum()

id               0
username       459
name             0
sex              0
address        563
              ...
Feature_86     300
Feature_87     281
Feature_88     360
Feature_89       0
PERFORMANCE      0
Length: 98, dtype: int64

In [ ]:
test_data.isnull().sum()

id             0
username      61
name           0
sex            0
address       58
              ..
Feature_85    31
Feature_86    34
Feature_87    32
Feature_88    43
Feature_89     0
Length: 97, dtype: int64

In [ ]:
# Replace 'Feature_0' and 'Feature_89' with the actual column names
start_column = 'Feature_0'
end_column = 'Feature_89'

# Get the range of columns
feature_columns = train_data.loc[:, start_column:end_column].columns

# Fill null values with the mode of each column
train_data[feature_columns] = train_data[feature_columns].apply(lambda x: x.fillna(x.mode().iloc[0]))

In [ ]:
train_data.isnull().sum()

id               0
username       459
name             0
sex              0
address        563
              ...
Feature_86       0
Feature_87       0
Feature_88       0
Feature_89       0
PERFORMANCE      0
Length: 98, dtype: int64

In [ ]:
# Replace 'Feature_0' and 'Feature_89' with the actual column names
start_column = 'Feature_0'
end_column = 'Feature_89'

# Get the range of columns
feature_columns = test_data.loc[:, start_column:end_column].columns

# Fill null values with the mode of each column
test_data[feature_columns] = test_data[feature_columns].apply(lambda x: x.fillna(x.mode().iloc[0]))

In [ ]:
test_data.isnull().sum()

id             0
username      61
name           0
sex            0
address       58
              ..
Feature_85     0
Feature_86     0
Feature_87     0
Feature_88     0
Feature_89     0
Length: 97, dtype: int64

In [ ]:
train_data['PERFORMANCE'].unique()

array(['Good', 'Outstanding', 'Satisfactory', 'Exceptional',
       'Below Expectations'], dtype=object)

In [ ]:
# Use LabelEncoder to convert string labels to numerical labels
label_encoder = LabelEncoder()
train_data['PERFORMANCE'] = label_encoder.fit_transform(train_data['PERFORMANCE'])

In [ ]:
#Display the mapping between original labels and numerical labels
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Label mapping:", label_mapping)

Label mapping: {'Below Expectations': 0, 'Exceptional': 1, 'Good': 2, 'Outstanding': 3, 'Satisfactory': 4}

In [ ]:
import pandas as pd

# Identify columns with the object data type
object_columns = train_data.select_dtypes(include=['object']).columns

# Remove columns with the object data type
train_data = train_data.drop(object_columns, axis=1)

In [ ]:
train_data

,id,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_7,Feature_8,Feature_10,Feature_11,...,Feature_80,Feature_81,Feature_82,Feature_83,Feature_84,Feature_85,Feature_86,Feature_87,Feature_88,PERFORMANCE
0,0,607.448272,894.186763,1926.578518,1771.167533,698.204167,549.414832,1209.948853,2371.668642,396.236073,...,16.611934,1450.571669,769.064513,276.428084,1571.997218,119.230563,290.957454,526.095944,246.874785,2
1,1,590.465102,911.188684,1863.216636,1667.902335,669.142576,569.181063,1173.697289,2364.452718,402.317593,...,18.243172,1497.975968,794.324022,290.593558,1635.521978,125.688701,408.768565,527.318691,258.141106,3
2,2,558.317650,843.646268,1905.089677,1732.639891,669.802383,564.564528,1251.815761,2405.063903,403.953384,...,-5.093898,1535.810436,840.543983,301.353124,1590.697352,113.951992,330.217298,539.402950,244.894605,4
3,5,584.180530,868.573535,1876.145309,1635.474354,658.442364,539.826701,1188.531202,2355.310978,399.198362,...,17.971081,1504.719587,818.188731,317.532936,1641.655406,120.452427,416.044019,538.388861,255.926962,1
4,6,625.779465,858.004091,1823.093229,1703.968285,687.849881,570.243271,1192.732615,2310.713894,401.269293,...,-9.463915,1458.575222,760.375257,284.687015,1660.299466,120.131530,399.738861,517.616502,237.514073,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134995,149995,570.877244,895.687867,1887.761799,1729.647579,663.581916,585.591344,1252.004161,2416.998837,404.530544,...,33.576963,1439.668987,807.367706,257.002048,1569.592285,116.360753,270.819039,532.531260,236.775788,1
134996,149996,577.943335,883.415622,1893.884950,1722.987999,673.319288,551.873396,1178.239928,2389.492948,397.927948,...,-3.414972,1530.500343,788.121862,323.406140,1628.618225,121.187883,402.986438,517.091594,258.142606,3
134997,149997,568.702333,873.418642,1924.534862,1692.699448,678.515557,550.580096,1214.766203,2345.486444,405.160795,...,28.797064,1508.928481,807.899584,307.125770,1640.264970,122.152608,392.498857,533.972709,243.785218,1
134998,149998,585.898561,872.186267,1885.916945,1717.002481,676.201427,545.904562,1203.584727,2414.288785,395.876152,...,33.435150,1443.252815,746.911527,315.400113,1676.560238,121.214616,400.994288,536.082192,226.900097,0
134999,149999,590.354431,893.904613,1881.190071,1673.666302,677.842858,557.655467,1152.464752,2322.957097,401.044966,...,-2.607993,1425.452109,743.667046,275.379830,1645.968979,124.726710,398.336179,545.061698,251.352538,4

In [ ]:
import pandas as pd

# Identify columns with the object data type
object_columns = test_data.select_dtypes(include=['object']).columns

# Remove columns with the object data type
test_data = test_data.drop(object_columns, axis=1)

In [ ]:
test_data

,id,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_7,Feature_8,Feature_10,Feature_11,...,Feature_77,Feature_80,Feature_81,Feature_82,Feature_83,Feature_84,Feature_85,Feature_86,Feature_87,Feature_88
0,133822,633.939127,860.678124,1890.639868,1599.125832,700.065894,560.478400,1142.306318,2324.498120,404.043779,...,236.252720,4.060968,1405.295290,765.671325,344.056134,1642.206290,121.999098,405.548449,513.006760,259.146116
1,111280,530.081446,879.140413,1956.431980,1715.768822,691.093618,573.900324,1225.238107,2394.963381,396.007396,...,221.116923,35.229351,1450.475104,801.414014,255.226679,1576.850676,120.248716,298.277468,557.458820,245.909248
2,41896,588.897216,890.571022,1857.052378,1680.794802,679.307214,545.563921,1221.336778,2375.785050,402.646875,...,218.828017,-7.904388,1482.772106,799.702911,319.761308,1654.732784,123.243748,394.411142,545.446459,235.604568
3,12400,580.444619,886.302033,1927.879685,1737.813633,677.588663,572.377322,1224.939141,2357.492665,406.090737,...,212.317209,10.755755,1401.287707,753.774289,268.812138,1615.592031,119.910907,310.873449,565.570126,227.619120
4,91525,574.496042,880.139277,1872.494311,1765.080595,677.712979,561.212732,1189.639693,2402.947094,397.143725,...,212.730746,9.938854,1462.806854,748.549407,281.382465,1617.677793,122.624388,350.918433,541.277451,244.110133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,47193,598.431772,902.592251,1893.713742,1761.146453,660.864936,551.340171,1232.286150,2332.385147,393.314965,...,234.838996,-10.749140,1517.548202,802.439055,289.831241,1606.044163,118.911055,341.754275,525.140123,241.993869
14996,121348,594.142135,867.144789,1898.577334,1641.449342,676.056805,561.088504,1171.159034,2389.671698,402.787958,...,233.569938,-5.932307,1488.220307,798.902793,220.424590,1640.947548,122.763637,416.160256,529.216656,258.554829
14997,27376,617.614041,870.315352,1894.579948,1789.802249,689.580030,565.688212,1200.783249,2328.007862,402.686740,...,227.567620,18.668836,1493.447497,750.510794,282.622375,1633.347335,120.923122,368.267812,536.622399,238.976516
14998,3745,631.012641,897.916977,1885.590200,1672.484018,678.695692,566.882780,1237.135346,2387.538272,398.268818,...,239.129828,-22.216622,1462.460785,836.348196,255.902492,1569.653394,118.410108,298.532520,537.433063,249.564188
14999,87506,637.783986,876.165803,1891.408785,1722.099579,672.958504,584.294083,1164.339043,2323.908209,398.659991,...,213.716734,6.801341,1489.304463,758.629252,280.864414,1638.846364,123.293942,402.862088,517.154530,254.161937

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

In [ ]:
# Split the data into features (X) and target variable (y)
X_train = train_data.drop('PERFORMANCE', axis=1)
y_train = train_data['PERFORMANCE']

In [ ]:
# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [ ]:
# Initialize XGBoost classifier
model = XGBClassifier()

# Train the model on the training set
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [ ]:
# Make predictions on the validation set
val_predictions = model.predict(X_val)

# Evaluate the accuracy of the model on the validation set
accuracy = accuracy_score(y_val, val_predictions)
print(f"Accuracy on validation set: {accuracy:.2f}")

Accuracy on validation set: 0.89

In [ ]:
# predictions on the test data
test_predictions = model.predict(test_data)

# Create a new DataFrame to store the results
result_df = pd.DataFrame({
    'id': test_data['id'],
    #'Predicted_Performance': test_predictions,
    'PERFORMANCE': [next(key for key, value in label_mapping.items() if value == pred) for pred in test_predictions]
})

In [ ]:
# Save the results to a new CSV file
result_df.to_csv('/content/drive/MyDrive/predicted_performance.csv', index=False)